name: Deploy Cobalt Site

on:
  push:
    branches:
      - main 
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build-and-deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Cobalt
        run: |
          curl -LSfs https://raw.githubusercontent.com/crate-ci/gh-install/master/v1/install.sh | sh -s -- --git cobalt-org/cobalt.rs --crate cobalt

      - name: Build Site
        run: cobalt build

      - name: Fingerprint site.css
        run: ./tasks/fingerprint _site

      - name: Validate HTML
        run: npx --yes html-validate "_site/**/*.html"

      - name: Check links
        uses: lycheeverse/lychee-action@v2
        with:
          args: --root-dir ${{ github.workspace }}/_site ./_site
          fail: true

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './_site'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
